# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site language
lang: en-US

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# The shortname for your Disqus site to enable comments.
disqus: cnshing
comments: true

# Whether to show authors at the end of each post
show_authors: false

title: Shing Chan's Tech World
email: chan.shing@protonmail.com
domain: cnshing.github.io
description: >- # this means to ignore newlines until "baseurl:"
  A blog describing interesting stories on the world of tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cnshing.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: cnshing
github_username:  cnshing

# Build settings
remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site navigation - each item must have a title and a url.
navigation:
  - text: Github
    url: https://github.com/cnshing
  - text: Sort by tags
    url: /tags/
  - text: Contact
    url: /contact/


# Colors
accent_colors:
  primary: '#3c77c1'
  border: '#b6d8ff'

# Site footer
footer:
  content: ""
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/posts/:num'

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
  animation_scale: 1.00 #Multiply animation duration by this amount
  animation_delay: 0.2565 #Multiply animation delay by this amount. If not specified, default to animation_scale.